### ISSUE TITLE
Unable to select flair, throws an error

### ISSUE THREAD

**Issue by Venefilyn** [Fedora-dotnet/verification-fas-discord-reddit#34]
With the list of flairs the user can select, once a user selects a flair the application will display an error.

Steps:

1. User logs in with Red Hat
1. User logs in with Reddit
1. User selects Red Hat Employee flair

Expected Results

1. User gets the assigned flair

Actual Results

1. An error occurs

**Comment by RheaAyase** [comment]
From stack it has a wrong reference. 

```
Aug 30 16:29:20 Keyra VerificationWeb[1776999]: System.TypeLoadException: Could not load type 'System.Collections.Generic.IAsyncEnumerable`1' from assembly 'System.Interactive.Async, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters() in /_/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 115
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at System.Reflection.RuntimeMethodInfo.GetParameters() in /_/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 371
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType(Type type, List`1& onSerializing, List`1& onSerialized, List`1& onDeserializing, List`1& onDeserialized, List`1& onError)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveCallbackMethods(JsonContract contract, Type t)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in /_/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1002
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at RedditSharp.Helpers.PopulateObject(JToken json, Object obj)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at RedditSharp.Things.Thing.Populate(JToken json)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at RedditSharp.Things.Thing..ctor(IWebAgent agent, JToken json, AuthenticatedUser user)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at RedditSharp.Things.Subreddit..ctor(IWebAgent agent, JToken json)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at RedditSharp.Things.Thing.Parse(IWebAgent agent, JToken json)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at RedditSharp.Things.Thing.Parse[T](IWebAgent agent, JToken json)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at RedditSharp.Helpers.GetThingAsync[T](IWebAgent agent, String url)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at VerificationWeb.Controllers.RoleController.GetRedditFlair(String flair) in /home/project/www/verification-fas-discord-reddit/VerificationWeb/Controllers/RoleController.cs:line 115
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Aug 30 16:29:20 Keyra VerificationWeb[1776999]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by RheaAyase** [comment]
https://github.com/CrustyJew/RedditSharp/issues/232
